context.modules = [
    {   name = libpipewire-module-loopback
        args = {
            node.description = "Reversed Stereo Output"
            capture.props = {
                node.name      = "reverse_stereo_capture"
                media.class    = "Audio/Sink"
                audio.position = [ FL FR ]
            }
            playback.props = {
                node.name      = "reverse_stereo_playback"
                audio.position = [ FR FL ]
                node.passive   = true
            }
        }
    }
]
